import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Eagles Shop",
  description: "Generated by create next app",
};

import { Providers } from './providers'

export default function RootLayout({
  children,
}: {
  children: React.ReactNode,
}) {
  return (
    <html lang='en'>
      <body>
        <Providers>{children}</Providers>
      </body>
    </html>
  )
}
